import { ObjectSampler } from './utils.js';

export const animations = new ObjectSampler()
    .put("null.js", 0)
    .put("sfc.js", 2)
    .put("saw.js", 2)
    .put("rndfill.js", 1)
    .put("eratosthenes.js", 2)
    .put("knightstour.js", 2)
    .put("textgen.js", 3)
    .put("tenprint.js", 3)
    .put("circ.js", 1)
    .put("tris.js", 1)
    .put("heart.js", 0.1)
    .put("simplex_growth.js", 1.25)
    .put("mapgen.js", 2)
    .put("dvdball.js", 1)
    .put("dog.js", 0.75)
    .put("bresenham_bounce.js", 1.5)
    .put("flow_fields.js", 3)
    .put("clock.js", 1)
    .put("sand.js", 4)
    .put("fractal.js", 4)
    .put("1d_automata.js", 2)
    .put("2d_automata.js", 6)
    .put("langtons_ant.js", 3)
    .put("cyclic_ca.js", 1)
    .put("boids.js", 3)
    .put("gas.js", 3)
    .put("voronoi.js", 3)
    .put("worley.js", 3)
    .put("lissajous.js", 3)
    .put("fluid.js", 3)
    .put("bytebeat.js", 3)
    .put("dla.js", 2)
    .put("physarum.js", 3)
    .put("raster.js", 3)
    .put("reacdiff.js", 3);
